### ISSUE TITLE
Liteeth driver not up to date ?

### ISSUE THREAD

**Issue by mczerski** [litex-hub/barebox#1]
It seems that the liteeth driver has different register map than the current hdl part. Which version of hdl this driver support ?

**Comment by frantony** [comment]
> It seems that the liteeth driver has different register map than the current hdl part. Which version of hdl this driver support ?

This driver supports mid-2020 version of hdl.

I need some time to adapt driver for new version.

Is there any need to support both versions of hdl in barebox driver?

**Comment by mczerski** [comment]
I made a pull request that adapts the driver to the current hdl version (#2 )

**Comment by enjoy-digital** [comment]
@frantony: Just for info, the only difference with mid-2020 version is just probably that the default CSR-data-width has been changed from 8-bit to 32-bit. You can eventually get back to 8-bit data-width by passing --csr-data-width=8 to the target file. On Linux SoC we however now try to only use 32-bit, so I would recommend updating.

**Comment by frantony** [comment]
I have just published my version of pre-built images for booting linux with barebox on Arty:
https://github.com/frantony/arty-linux-on-litex-vexriscv-prebuilt

Latest barebox https://github.com/litex-hub/barebox/tree/20210813.litex-vexriscv-linux works fine with latest liteeth.
